# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... } : {

  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ahci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/79a7f989-ed8e-4ebc-b978-7438f581280d";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/24094347-93ac-4d84-921f-ab8e523af308"; }
  ];

  nix.maxJobs = 1;

}
