# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3c196574-9e41-4022-a55e-3c881e2b1260";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker" =
   { device = "/dev/disk/by-label/docker";
     fsType = "ext4";
   };

  swapDevices = [ ];

  nix.maxJobs = 2;
  virtualisation.virtualbox.guest.enable = true;
}
