name: xmonad-config

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns

when:
  - condition: os(darwin)
    extra-lib-dirs:
      - /usr/X11/lib
    include-dirs:
      - /usr/X11/include

executables:
  xmonad-config:
    main: src/Main.hs
    dependencies:
      - base
      - xmonad
      - xmonad-contrib
      - xmonad-extras
