comma-style: leading
fixities: []
function-arrows: leading
haddock-style-module:
haddock-style: single-line
import-export-style: leading
in-style: right-align
indent-wheres: false
indentation: 2
let-style: auto
newlines-between-decls: 1
record-brace-space: false
respectful: true
unicode: never
