comma-style: leading
function-arrows: leading
haddock-style-module: single-line
haddock-style: single-line
import-export-style: leading
in-style: left-align
indent-wheres: true
indentation: 2
let-style: auto
newlines-between-decls: 1
record-brace-space: false
respectful: true
unicode: never
fixities: []
