#!/bin/bash

# exports

export EDITOR=emacsclient
export VISUAL=$EDITOR

export GNUPGHOME="$XDG_CONFIG_HOME/gnupg/gpg-agent.conf"

export NPM_CONFIG_PREFIX="$HOME/.local"

export WORDLIST="$XDG_CONFIG_HOME/ispell/words"

# aliases

alias ec='emacsclient -c'
alias em='emacsclient -n'
alias et='emacsclient -t'

alias scpq='scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias sshq='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

alias tmux="tmux -f '$XDG_CONFIG_HOME/tmux/conf'"

# functions

function sshqq() {
  local h1="${1:? Missing host 1}"
  local h2="${2:? Missing host 2}"
  sshq -A -t "$h1" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -t "$h2"
}

say-all() {
  say -v '?' | cut -d ' ' -f1 |
    while read v; do
      echo "$v"
      say -v "$v" 'the rain in spain falls mainly on the plain'
      sleep 0.25
    done
}

gpg-txz() {
  [[ $# -gt 0 ]] || fail "Usage: $0 <file.txz.gpg | file | name file [file]*>"
  local name=$1
  if [[ $# -eq 1 ]]; then
    if [[ "$name" = *.txz.gpg ]]; then
      gpg -d "$name" | tar xf -
      return 0
    else
      local files=$name
    fi
  else
    shift
    local files="$*"
  fi
  tar cJvf - $files | gpg --symmetric --cipher-algo aes256 -o "${name}.txz.gpg"
}

tmux-share() {
  local name=${1:-shared}
  local socket=
  socket="/tmp/$(whoami)-tmux-$name"
  echo "to connect:  tmux -S '$socket' attach -t $name"
  touch "$socket"
  chgrp sysadmin "$socket"
  sleep 5
  tmux -S "$socket" new -s "$name"
}

upcase() {
  tr '[:lower:]' '[:upper:]' <<< "$@"
}

# Creates a private key, CSR, and pem in the current dir.
tls-new() {
  local cn="${1:? Missing cn}"
  local name="${2:-$(sed 's/\*\.//' <<< "$1" | sed 's/\./-/g')}"
  local key="$name.key"

  openssl req -new -newkey rsa:4096 -sha512 -nodes \
          -subj "/CN=$cn/" \
          -out "$name.csr" \
          -keyout "$key" \
    && openssl rsa -in "$key" -outform pem \
               -out "$name.pem"
}
