#!/usr/bin/env bash

alias sghc='stack ghc --'
alias sghci='stack ghci --'
alias sghcr='stack runghc'

# the database folder in /nix/store is not writable
hoo() {
  hoogle "$@" -d "$XDG_DATA_HOME/hoogle"
}
