[buildPlans.iosevka-terminal]
family = "Iosevka Terminal"
spacing = "term"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.iosevka-terminal.variants.design]
capital-i = "short-serifed"
capital-j = "serifless"
i = "hooky"
j = "serifless"
l = "zshaped"
m = "short-leg"
t = "flat-hook-short-neck"
capital-gamma = "motion-serifed"
latn-epsilon = "serifed"
latn-reverse-epsilon = "serifed"
lower-iota = "serifed-tailed"
lower-lambda = "straight-turn"
cyrl-ka = "straight-motion-serifed"
zero = "dotted"
one = "base"
two = "straight-neck"
three = "flattop"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
seven = "straight-crossbar"
eight = "two-circles"
asterisk = "hex-high"
brace = "straight"
number-sign = "upright"
at = "fourfold"
dollar = "interrupted"
percent = "rings-continuous-slash"

[buildPlans.iosevka-terminal.weights.extralight]
shape = 200
menu = 200
css = 200

[buildPlans.iosevka-terminal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-terminal.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-terminal.slopes]
upright = "normal"
italic = "italic"
