[buildPlans.iosevka-haskell]
family = "Iosevka Haskell"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-haskell.variants.design]
capital-i = "short-serifed"
capital-j = "serifless"
i = "hooky"
j = "serifless"
l = "zshaped"
m = "short-leg"
t = "flat-hook-short-neck"
capital-gamma = "serifed"
latn-epsilon = "serifed"
latn-reverse-epsilon = "serifed"
lower-iota = "serifed-tailed"
lower-lambda = "straight-turn"
cyrl-ka = "straight-motion-serifed"
zero = "dotted"
one = "base"
two = "straight-neck"
three = "flattop"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
seven = "straight-crossbar"
eight = "two-circles"
asterisk = "hex-high"
brace = "straight"
number-sign = "upright"
at = "fourfold"
dollar = "interrupted"
percent = "rings-continuous-slash"

[buildPlans.iosevka-haskell.ligations]
inherits = "haskell"

[buildPlans.iosevka-haskell.weights.thin]
shape = 100
menu = 100
css = 100

[buildPlans.iosevka-haskell.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-haskell.weights.bold]
shape = 700
menu = 700
css = 700
